repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        additional_dependencies: [types-python-dateutil]
        args: [--ignore-missing-imports]

  - repo: local
    hooks:
      - id: coverage-check
        name: Coverage Quality Gate (A+ Standard)
        entry: python -m pytest --cov=src --cov-fail-under=85 --cov-report=term-missing -x
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]
        verbose: true

      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: [--tb=short]
      - id: check-excluded
        name: Check excluded wrapper files
        entry: python tools/pre_commit/check_excluded.py
        language: python
        pass_filenames: false
        stages: [commit, push]
