name: Test and upload per-test logs on failure

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if test -f requirements.txt; then pip install -r requirements.txt; fi

      - name: Run tests
        id: run_tests
        run: |
          # Ensure log dir exists
          mkdir -p test-logs || true
          # Run pytest; logs will be created by the test fixture.
          python -m pytest -q || exit 1

      - name: Upload test logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-logs-${{ github.run_id }}
          path: test-logs
          retention-days: 7
